const { withDangerousMod } = require("@expo/config-plugins");
const path = require("path");
const fs = require("fs");

/**
 * Expo config plugin for @crossmint/expo-device-signer.
 *
 * 1. Injects a `pod 'CrossmintDeviceSigner'` entry so CocoaPods can resolve
 *    the Swift SDK pod that ExpoDeviceSigner depends on.
 *
 * 2. Injects CrossmintDeviceSigner exclusion code into the existing
 *    `post_install` block to avoid duplicate symbol errors from Expo
 *    autolinking trying to compile DeviceSignerModule.swift twice.
 */
const withDeviceSigner = (config) => {
    return withDangerousMod(config, [
        "ios",
        async (config) => {
            const podfilePath = path.join(config.modRequest.platformProjectRoot, "Podfile");
            let podfile = fs.readFileSync(podfilePath, "utf8");

            // --- 1. CrossmintDeviceSigner pod source ---
            const podEntry = `  # @crossmint/expo-device-signer: CrossmintDeviceSigner (hardware-backed key storage)
  pod 'CrossmintDeviceSigner', :git => 'https://github.com/Crossmint/crossmint-swift-sdk.git', :tag => '0.11.0'
`;
            if (!podfile.includes("CrossmintDeviceSigner")) {
                // Insert right after `use_expo_modules!`, which is always inside the target block.
                podfile = podfile.replace(/(use_expo_modules!)/, `$1\n\n${podEntry}`);
            }

            // --- 2. Work around Expo SDK 54 + React Native 0.82 header incompatibility ---
            // With RCT_USE_PREBUILT_RNCORE=1: React-Core-umbrella.h not found.
            // Without it: CallInvoker not found (moved in RN 0.82).
            // Fix: unset prebuilt flags so React-Core compiles from source.
            if (!podfile.includes("CROSSMINT_RN_PREBUILT_FIX")) {
                podfile = podfile.replace(
                    /(ENV\['RCT_USE_RN_DEP'\][^\n]+\n)(ENV\['RCT_USE_PREBUILT_RNCORE'\][^\n]+\n)/,
                    `$1$2ENV.delete('RCT_USE_RN_DEP')         # CROSSMINT_RN_PREBUILT_FIX\nENV.delete('RCT_USE_PREBUILT_RNCORE')  # CROSSMINT_RN_PREBUILT_FIX\n`
                );
            }

            // --- 3. Inject into the existing post_install block ---
            // CocoaPods only allows one post_install block; we must inject into it.
            const injectionMarker = "# @crossmint/expo-device-signer: CrossmintDeviceSigner autolinking exclusion";
            if (!podfile.includes(injectionMarker)) {
                const injection = `    ${injectionMarker}
    # RN 0.82 removed CallInvoker.h from TurboModuleUtils.h, breaking
    # expo-modules-core@3.x. Inject it via a prefix header for that pod.
    require 'fileutils'
    pch_path = "#{installer.sandbox.root}/CrossmintExpoFixes.pch"
    unless File.exist?(pch_path)
      File.write(pch_path, [
        "// Auto-generated by @crossmint/expo-device-signer plugin",
        "#ifdef __OBJC__",
        "#endif",
        "#ifdef __cplusplus",
        "// RN 0.82 moved these headers; include from their new locations.",
        "#include <ReactCommon/CallInvoker.h>",
        "#include <ReactCommon/react/bridging/CallbackWrapper.h>",
        "#endif",
      ].join("\\n") + "\\n")
    end
    installer.pods_project.targets.each do |target|
      if target.name == 'ExpoModulesCore'
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREFIX_HEADER'] = pch_path
          config.build_settings['GCC_PRECOMPILE_PREFIX_HEADER'] = 'YES'
          paths = config.build_settings['HEADER_SEARCH_PATHS'] || '$(inherited)'
          # Needed so <ReactCommon/CallInvoker.h> resolves correctly
          extra = '$(PODS_ROOT)/Headers/Public/React-callinvoker'
          config.build_settings['HEADER_SEARCH_PATHS'] = "#{paths} #{extra}" unless paths.include?(extra)
        end
      end
      if target.name == 'CrossmintDeviceSigner'
        target.build_configurations.each do |config|
          config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = ''
        end
      end
    end
`;
                // Insert at the top of the post_install block, right after the opening line.
                podfile = podfile.replace(/(post_install do \|installer\|)/, `$1\n${injection}`);
            }

            fs.writeFileSync(podfilePath, podfile);
            return config;
        },
    ]);
};

module.exports = withDeviceSigner;
