import type { BlockchainIncludingTestnet } from "../types";

export const BLOCKCHAIN_TO_COPY_NAME: Record<BlockchainIncludingTestnet, string> = {
    aptos: "Aptos",
    solana: "Solana",
    ethereum: "Ethereum",
    "ethereum-sepolia": "Ethereum Sepolia",
    "ethereum-goerli": "Ethereum Goerli",
    polygon: "Polygon",
    "polygon-mumbai": "Polygon Mumbai",
    "polygon-amoy": "Polygon Amoy Testnet",
    bsc: "BNB Smart Chain",
    "bsc-testnet": "BNB Smart Chain Testnet",
    sui: "Sui",
    optimism: "Optimism",
    "optimism-goerli": "Optimism Goerli",
    "optimism-sepolia": "Optimism Sepolia",
    arbitrum: "Arbitrum",
    "arbitrum-sepolia": "Arbitrum Sepolia",
    arbitrumnova: "Arbitrum Nova",
    base: "Base",
    "base-goerli": "Base Goerli",
    "base-sepolia": "Base Sepolia",
    zora: "Zora",
    "zora-goerli": "Zora Goerli",
    "zora-sepolia": "Zora Sepolia",
    zkatana: "zKatana",
    zkyoto: "zKyoto",
    "astar-zkevm": "Astar zkEVM",
    "hypersonic-testnet": "Hypersonic Testnet",
    "story-testnet": "Story Testnet",
    story: "Story Mainnet",
    "mode-sepolia": "Mode Sepolia",
    mode: "Mode",
    chiliz: "Chiliz",
    shape: "Shape",
    "world-chain": "Worldchain",
    abstract: "Abstract",
    apechain: "ApeChain",
    mantle: "Mantle",
    scroll: "Scroll",
    "sei-pacific-1": "Sei Pacific",
    "abstract-testnet": "Abstract Testnet",
    curtis: "Curtis",
    "mantle-sepolia": "Mantle Sepolia",
    "scroll-sepolia": "Scroll Sepolia",
    "sei-atlantic-2-testnet": "Sei Atlantic Testnet",
    "world-chain-sepolia": "Worldchain Sepolia",
    flow: "Flow",
    "flow-testnet": "Flow Testnet",
    plume: "Plume",
    "plume-testnet": "Plume Testnet",
    "arc-testnet": "Arc Testnet",
};

export function blockchainToDisplayName(blockchain: BlockchainIncludingTestnet) {
    return BLOCKCHAIN_TO_COPY_NAME[blockchain];
}
