import type { BlockchainIncludingTestnet } from "../types";

export const BLOCKCHAIN_TO_COPY_NAME: Record<BlockchainIncludingTestnet, string> = {
    aptos: "Aptos",
    solana: "Solana",
    ethereum: "Ethereum",
    "ethereum-sepolia": "Ethereum Sepolia",
    polygon: "Polygon",
    "polygon-amoy": "Polygon Amoy Testnet",
    bsc: "BNB Smart Chain",
    "bsc-testnet": "BNB Smart Chain Testnet",
    sui: "Sui",
    optimism: "Optimism",
    "optimism-sepolia": "Optimism Sepolia",
    arbitrum: "Arbitrum",
    "arbitrum-sepolia": "Arbitrum Sepolia",
    arbitrumnova: "Arbitrum Nova",
    base: "Base",
    "base-sepolia": "Base Sepolia",
    zora: "Zora",
    "zora-sepolia": "Zora Sepolia",
    "hypersonic-testnet": "Hypersonic Testnet",
    "story-testnet": "Story Testnet",
    story: "Story Mainnet",
    chiliz: "Chiliz",
    shape: "Shape",
    abstract: "Abstract",
    apechain: "ApeChain",
    mantle: "Mantle",
    scroll: "Scroll",
    "sei-pacific-1": "Sei Pacific",
    "abstract-testnet": "Abstract Testnet",
    curtis: "Curtis",
    "mantle-sepolia": "Mantle Sepolia",
    "scroll-sepolia": "Scroll Sepolia",
    "sei-atlantic-2-testnet": "Sei Atlantic Testnet",
    flow: "Flow",
    "flow-testnet": "Flow Testnet",
    arc: "Arc",
    "arc-testnet": "Arc Testnet",
    tempo: "Tempo",
    "tempo-testnet": "Tempo Testnet",
    avalanche: "Avalanche",
    "avalanche-fuji": "Avalanche Fuji",
    celo: "Celo",
    "celo-sepolia": "Celo Sepolia",
    "robinhood-chain": "Robinhood Chain",
    "robinhood-chain-testnet": "Robinhood Chain Testnet",
};

export function blockchainToDisplayName(blockchain: BlockchainIncludingTestnet) {
    return BLOCKCHAIN_TO_COPY_NAME[blockchain];
}
