#!/usr/bin/env bash
# Prints the Paella-Labs/best-practices files listed in its manifest.txt, followed by
# the stack files passed as arguments (e.g. typescript.md). Stack files missing upstream
# are skipped. Results are cached per commit SHA and stack list.
# Usage: ./scripts/fetch-best-practices.sh [stack.md ...]

REPO="Paella-Labs/best-practices"
CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/paella-best-practices"
CACHE_FILE="$CACHE_DIR/best-practices.md"
CHECKED_FILE="$CACHE_DIR/checked"
mkdir -p "$CACHE_DIR"

STACKS="$*"

cached_key() {
    sed -n '1s/^<!-- key: \(.*\) -->$/\1/p' "$CACHE_FILE"
}

cache_matches() {
    [ -f "$CACHE_FILE" ] || return 1
    head -n 1 "$CACHE_FILE" | grep -q '^<!-- key: ' || return 1
    [ "$(cached_key | cut -d' ' -f2-)" = "$STACKS" ]
}

serve_cache() {
    if cache_matches; then
        cat "$CACHE_FILE"
        exit 0
    fi
    echo "fetch-best-practices: could not fetch best practices${STACKS:+ with $STACKS} from $REPO and no cached copy for that stack list exists" >&2
    exit 1
}

NOW=$(date +%s)
LAST_CHECKED=0
[ -f "$CHECKED_FILE" ] && LAST_CHECKED=$(cat "$CHECKED_FILE")
case "$LAST_CHECKED" in '' | *[!0-9]*) LAST_CHECKED=0 ;; esac
if [ $((NOW - LAST_CHECKED)) -lt 86400 ] && cache_matches; then
    serve_cache
fi

LATEST_SHA=$(gh api "repos/$REPO/git/ref/heads/main" --jq '.object.sha' 2>/dev/null)
if [ -z "$LATEST_SHA" ]; then
    serve_cache
fi

if cache_matches && [ "$(cached_key)" = "$LATEST_SHA $STACKS" ]; then
    echo "$NOW" > "$CHECKED_FILE"
    serve_cache
fi

TMP_FILE=$(mktemp "$CACHE_DIR/best-practices.XXXXXX") || serve_cache
ERR_FILE="$TMP_FILE.err"
trap 'rm -f "$TMP_FILE" "$ERR_FILE"' EXIT

fetch_file() {
    gh api "repos/$REPO/contents/$1?ref=$LATEST_SHA" -H "Accept: application/vnd.github.raw" 2>"$ERR_FILE"
}

MANIFEST=$(fetch_file manifest.txt) || serve_cache
FILES=$(printf '%s\n' "$MANIFEST" | grep -Ev '^[[:space:]]*(#|$)')

{
    echo "<!-- key: $LATEST_SHA $STACKS -->"
    echo "<!-- Generated by scripts/fetch-best-practices.sh $STACKS on $(date -u '+%Y-%m-%d %H:%M:%S UTC') -->"
    echo ""
    echo "# Paella/Crossmint Best Practices"
    echo "Source: https://github.com/$REPO"
    echo ""
    echo "When generating any content, such as code, documentation, PRs, plans, design documents, or other outputs, ensure it adheres to the following best practices."
    echo ""
} > "$TMP_FILE" || serve_cache

for file in $FILES "$@"; do
    if content=$(fetch_file "$file"); then
        {
            echo "## $file"
            echo ""
            printf '%s\n' "$content" | sed -E 's/^(#+)/\1##/'
            echo ""
        } >> "$TMP_FILE" || serve_cache
    elif ! grep -q "HTTP 404" "$ERR_FILE"; then
        serve_cache
    fi
done

cat "$TMP_FILE"
mv "$TMP_FILE" "$CACHE_FILE"
echo "$NOW" > "$CHECKED_FILE"
