#!/bin/bash
# Fetches the given .md files from Paella-Labs/best-practices and prints them as one document.
# Usage: ./scripts/fetch-best-practices.sh core.md typescript.md
# Files missing upstream (404) are skipped. The result is cached by commit SHA and file list; GitHub is
# checked at most once every 24 hours, and a stale cache for the same file list is served when GitHub is
# unreachable. Exits non-zero when nothing can be fetched and no cache exists for the requested files.

REPO="Paella-Labs/best-practices"
CACHE_FILE="$HOME/.claude/paella-best-practices-cache.md"
CHECKED_FILE="$HOME/.claude/paella-best-practices-checked.txt"
LEGACY_KEY_FILE="$HOME/.claude/paella-best-practices-sha.txt"
mkdir -p "$HOME/.claude"

if [ "$#" -eq 0 ]; then
    set -- core.md
fi
FILES="$*"

# The first line of the cache records "<sha> <files>", so the document and its key are replaced atomically.
# Caches written by older versions of this script keep the key in a separate file instead.
cached_key() {
    [ -f "$CACHE_FILE" ] || return
    if head -n 1 "$CACHE_FILE" | grep -q '^<!-- key: '; then
        sed -n '1s/^<!-- key: \(.*\) -->$/\1/p' "$CACHE_FILE"
    elif [ -f "$LEGACY_KEY_FILE" ]; then
        cat "$LEGACY_KEY_FILE"
    fi
}

cached_files() {
    cached_key | cut -d' ' -f2-
}

serve_cache() {
    if [ "$(cached_files)" = "$FILES" ]; then
        cat "$CACHE_FILE"
        exit 0
    fi
    echo "fetch-best-practices: could not fetch $FILES from $REPO and no cached copy of those files exists" >&2
    exit 1
}

NOW=$(date +%s)
LAST_CHECKED=0
[ -f "$CHECKED_FILE" ] && LAST_CHECKED=$(cat "$CHECKED_FILE")
if [ $((NOW - LAST_CHECKED)) -lt 86400 ] && [ "$(cached_files)" = "$FILES" ]; then
    serve_cache
fi

LATEST_SHA=$(gh api "repos/$REPO/git/ref/heads/main" --jq '.object.sha' 2>/dev/null)
if [ -z "$LATEST_SHA" ]; then
    serve_cache
fi

if [ "$(cached_key)" = "$LATEST_SHA $FILES" ]; then
    echo "$NOW" > "$CHECKED_FILE"
    serve_cache
fi

TMP_FILE=$(mktemp "$HOME/.claude/paella-best-practices.XXXXXX")
ERR_FILE="$TMP_FILE.err"
trap 'rm -f "$TMP_FILE" "$ERR_FILE"' EXIT
{
    echo "<!-- key: $LATEST_SHA $FILES -->"
    echo "<!-- Generated by scripts/fetch-best-practices.sh $FILES on $(date -u '+%Y-%m-%d %H:%M:%S UTC') -->"
    echo ""
    echo "# Paella/Crossmint Best Practices"
    echo "Source: https://github.com/$REPO"
    echo ""
    echo "When generating any content, such as code, documentation, PRs, plans, design documents, or other outputs, ensure it adheres to the following best practices."
    echo ""
} > "$TMP_FILE"

for file in "$@"; do
    if content=$(gh api "repos/$REPO/contents/$file?ref=$LATEST_SHA" -H "Accept: application/vnd.github.raw" 2>"$ERR_FILE"); then
        {
            echo "## $file"
            echo ""
            printf '%s\n' "$content" | sed -E 's/^(#+)/\1##/'
            echo ""
        } >> "$TMP_FILE"
    elif ! grep -q "HTTP 404" "$ERR_FILE"; then
        # Any failure other than a missing file keeps the previous cache so the next run retries.
        serve_cache
    fi
done

cat "$TMP_FILE"
mv "$TMP_FILE" "$CACHE_FILE"
rm -f "$LEGACY_KEY_FILE"
echo "$NOW" > "$CHECKED_FILE"
