#!/bin/bash
# Fetches the given .md files from Paella-Labs/best-practices and prints them as one document.
# Usage: ./scripts/fetch-best-practices.sh core.md typescript.md
# Files missing upstream are skipped. The result is cached by commit SHA and file list; GitHub is
# checked at most once every 24 hours, and a stale cache is served when GitHub is unreachable.

REPO="Paella-Labs/best-practices"
CACHE_FILE="$HOME/.claude/paella-best-practices-cache.md"
KEY_FILE="$HOME/.claude/paella-best-practices-sha.txt"
CHECKED_FILE="$HOME/.claude/paella-best-practices-checked.txt"
mkdir -p "$HOME/.claude"

if [ "$#" -eq 0 ]; then
    set -- core.md
fi
FILES="$*"

serve_cache() {
    [ -f "$CACHE_FILE" ] && cat "$CACHE_FILE"
    exit 0
}

cached_files() {
    [ -f "$KEY_FILE" ] && cut -d' ' -f2- "$KEY_FILE"
}

NOW=$(date +%s)
LAST_CHECKED=0
[ -f "$CHECKED_FILE" ] && LAST_CHECKED=$(cat "$CHECKED_FILE")
if [ $((NOW - LAST_CHECKED)) -lt 86400 ] && [ "$(cached_files)" = "$FILES" ]; then
    serve_cache
fi

LATEST_SHA=$(gh api "repos/$REPO/git/ref/heads/main" --jq '.object.sha' 2>/dev/null)
if [ -z "$LATEST_SHA" ]; then
    serve_cache
fi

echo "$NOW" > "$CHECKED_FILE"

if [ -f "$CACHE_FILE" ] && [ "$(cat "$KEY_FILE" 2>/dev/null)" = "$LATEST_SHA $FILES" ]; then
    serve_cache
fi

TMP_FILE=$(mktemp)
{
    echo "<!-- Generated by scripts/fetch-best-practices.sh $FILES on $(date -u '+%Y-%m-%d %H:%M:%S UTC') -->"
    echo ""
    echo "# Paella/Crossmint Best Practices"
    echo "Source: https://github.com/$REPO"
    echo ""
    echo "When generating any content, such as code, documentation, PRs, plans, design documents, or other outputs, ensure it adheres to the following best practices."
    echo ""
} > "$TMP_FILE"

for file in "$@"; do
    # A missing file (404) is skipped so repos can list stack files before they exist upstream.
    if content=$(gh api "repos/$REPO/contents/$file?ref=$LATEST_SHA" -H "Accept: application/vnd.github.raw" 2>/dev/null); then
        {
            echo "## $file"
            echo ""
            printf '%s\n' "$content" | sed -E 's/^(#+)/\1##/'
            echo ""
        } >> "$TMP_FILE"
    fi
done

mv "$TMP_FILE" "$CACHE_FILE"
echo "$LATEST_SHA $FILES" > "$KEY_FILE"
cat "$CACHE_FILE"
