name: CI

env:
    NEXT_PUBLIC_CROSSMINT_API_KEY: ${{ secrets.NEXT_PUBLIC_CROSSMINT_AUTH_SMART_WALLET_API_KEY }}
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: ${{ vars.TURBO_TEAM }}

on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    build-and-test:
        name: Build & Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js, PNPM, and install dependencies
              uses: ./.github/actions/pnpm-install

            - name: Build all
              run: pnpm build

            - name: Test all
              run: pnpm test:vitest

    release:
        name: Release
        runs-on: ubuntu-latest
        needs: [build-and-test]
        permissions:
            contents: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js, PNPM, and install dependencies
              uses: ./.github/actions/pnpm-install

            - name: Create Release Pull Request or Publish
              uses: changesets/action@v1.5.3
              with:
                  commit: "Release packages"
                  title: "Release packages"
                  publish: pnpm change:publish
                  version: pnpm change:version
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
